version: 0.2

phases:
  phases:
    install:
      runtime-versions:
        java: corretto8
  build:
    commands:
      - mvn clean install
      - mvn spring-boot:run
  post_build:
    commands:
      - echo Build Completed
artifacts:
  files:
    - target/*jar
  discard-paths: yes